# Author: Green Mountain Systems AI Inc.
# Donated to IAB Tech Lab

"""Data models for the Ad Seller System."""

from .agent_registry import (
    TRUST_TO_TIER_MAP,
    AgentAuthentication,
    AgentCapabilities,
    AgentCard,
    AgentProvider,
    AgentSkill,
    AgentType,
    RegisteredAgent,
    RegistrySource,
    TrustStatus,
)
from .api_key import (
    ApiKeyCreateRequest,
    ApiKeyCreateResponse,
    ApiKeyInfo,
    ApiKeyRecord,
)
from .audience_capabilities import (
    AgenticCapabilities,
    AgenticCapabilityFlag,
    AudienceCapabilities,
    CapabilityAudienceBlock,
    MaxRefsPerRole,
    TaxonomyLockHashes,
    build_capability_audience_block,
    load_taxonomy_lock_hashes,
)
from .audience_ref import (
    AudienceRef,
    ComplianceContext,
)
from .buyer_identity import (
    AccessTier,
    BuyerContext,
    BuyerIdentity,
    IdentityLevel,
)
from .change_request import (
    ChangeRequest,
    ChangeRequestStatus,
    ChangeSeverity,
    ChangeType,
    FieldDiff,
    classify_severity,
    validate_change_request,
)
from .core import (
    Account,
    AccountStatus,
    ActorType,
    AdProfile,
    Assignment,
    ChangeClassification,
    CommercialTerms,
    Creative,
    CreativeAsset,
    CreativeManifest,
    DealType,
    DeliveryGoal,
    EntityMapping,
    ExecutionOrder,
    ExecutionOrderStatus,
    GoalType,
    InventorySegment,
    Organization,
    OrganizationRole,
    Placement,
    PlacementStatus,
    Pricing,
    PricingModel,
    Product,
    Proposal,
    ProposalLine,
    ProposalRevision,
    ProposalStatus,
    ProposalThread,
    ReviewStatus,
    RevisionStatus,
    RevisionType,
    RotationMode,
)
from .flow_state import (
    ChannelRecommendation,
    DealOutput,
    ExecutionStatus,
    PricingDecision,
    ProductDefinition,
    ProposalEvaluation,
    SellerFlowState,
)
from .gam import (
    AudienceSegmentMapping,
    GAMAdUnit,
    GAMAdUnitSize,
    GAMAdUnitTargeting,
    GAMAudienceSegment,
    GAMAudienceSegmentCriteria,
    GAMAudienceSegmentStatus,
    GAMAudienceSegmentType,
    GAMBookingResult,
    GAMCompany,
    GAMCostType,
    GAMCustomCriteriaSet,
    GAMDateTime,
    GAMGoal,
    GAMGoalType,
    GAMInventoryTargeting,
    GAMLineItem,
    GAMLineItemStatus,
    GAMLineItemType,
    GAMMoney,
    GAMOrder,
    GAMOrderStatus,
    GAMPrivateAuction,
    GAMPrivateAuctionDeal,
    GAMSize,
    GAMTargeting,
    GAMUnitType,
)
from .linear_tv import (
    Daypart,
    LinearDeal,
    LinearTVProduct,
    MakegoodTerms,
    SupplyPoolEntry,
)
from .media_kit import (
    AudienceCapabilityPublicSummary,
    AuthenticatedPackageView,
    Package,
    PackageLayer,
    PackagePlacement,
    PackageStatus,
    PublicPackageView,
)
from .negotiation import (
    STRATEGY_LIMITS,
    TIER_STRATEGY_MAP,
    NegotiationAction,
    NegotiationHistory,
    NegotiationLimits,
    NegotiationRound,
    NegotiationStrategy,
)
from .order_state_machine import (
    InvalidTransitionError,
    OrderAuditLog,
    OrderStateMachine,
    OrderStatus,
    StateTransition,
    TransitionRule,
    from_execution_order_status,
    from_execution_status,
)
from .pricing_tiers import (
    PricingRule,
    PricingTier,
    TieredPricingConfig,
    VolumeDiscount,
)
from .session import (
    NegotiationState,
    Session,
    SessionMessage,
    SessionStatus,
)
from .ucp import (
    AudienceCapability,
    AudiencePlan,
    AudienceValidationResult,
    CoverageEstimate,
    EmbeddingType,
    SignalType,
    SimilarityMetric,
    UCPConsent,
    UCPContextDescriptor,
    UCPEmbedding,
    UCPModelDescriptor,
)

__all__ = [
    # Core ad tech entities
    "Organization",
    "OrganizationRole",
    "Account",
    "AccountStatus",
    "InventorySegment",
    "Product",
    "CommercialTerms",
    "ProposalThread",
    "ProposalRevision",
    "RevisionType",
    "RevisionStatus",
    "ChangeClassification",
    "ActorType",
    "Proposal",
    "ProposalStatus",
    "ProposalLine",
    "DealType",
    "DeliveryGoal",
    "GoalType",
    "Pricing",
    "PricingModel",
    "ExecutionOrder",
    "ExecutionOrderStatus",
    "Placement",
    "PlacementStatus",
    "Creative",
    "AdProfile",
    "CreativeManifest",
    "CreativeAsset",
    "ReviewStatus",
    "Assignment",
    "RotationMode",
    "EntityMapping",
    # Flow state
    "SellerFlowState",
    "ExecutionStatus",
    "ProductDefinition",
    "ProposalEvaluation",
    "PricingDecision",
    "ChannelRecommendation",
    "DealOutput",
    # Buyer identity
    "BuyerIdentity",
    "BuyerContext",
    "AccessTier",
    "IdentityLevel",
    # Session
    "Session",
    "SessionStatus",
    "SessionMessage",
    "NegotiationState",
    # Pricing tiers
    "PricingTier",
    "PricingRule",
    "VolumeDiscount",
    "TieredPricingConfig",
    # UCP models
    "AudienceCapability",
    "AudiencePlan",
    "AudienceValidationResult",
    "CoverageEstimate",
    "EmbeddingType",
    "SignalType",
    "SimilarityMetric",
    "UCPConsent",
    "UCPContextDescriptor",
    "UCPEmbedding",
    "UCPModelDescriptor",
    # Media kit
    "Package",
    "PackageLayer",
    "PackageStatus",
    "PackagePlacement",
    "PublicPackageView",
    "AuthenticatedPackageView",
    "AudienceCapabilityPublicSummary",
    # Audience capabilities (proposal §5.7)
    "AudienceCapabilities",
    "AgenticCapabilities",
    "AgenticCapabilityFlag",
    "AudienceRef",
    "ComplianceContext",
    "CapabilityAudienceBlock",
    "MaxRefsPerRole",
    "TaxonomyLockHashes",
    "build_capability_audience_block",
    "load_taxonomy_lock_hashes",
    # Negotiation
    "NegotiationAction",
    "NegotiationHistory",
    "NegotiationLimits",
    "NegotiationRound",
    "NegotiationStrategy",
    "STRATEGY_LIMITS",
    "TIER_STRATEGY_MAP",
    # GAM models
    "GAMAdUnit",
    "GAMAdUnitSize",
    "GAMAdUnitTargeting",
    "GAMAudienceSegment",
    "GAMAudienceSegmentCriteria",
    "GAMAudienceSegmentStatus",
    "GAMAudienceSegmentType",
    "GAMBookingResult",
    "GAMCompany",
    "GAMCostType",
    "GAMCustomCriteriaSet",
    "GAMDateTime",
    "GAMGoal",
    "GAMGoalType",
    "GAMInventoryTargeting",
    "GAMLineItem",
    "GAMLineItemStatus",
    "GAMLineItemType",
    "GAMMoney",
    "GAMOrder",
    "GAMOrderStatus",
    "GAMPrivateAuction",
    "GAMPrivateAuctionDeal",
    "GAMSize",
    "GAMTargeting",
    "GAMUnitType",
    "AudienceSegmentMapping",
    # Linear TV models
    "Daypart",
    "LinearDeal",
    "LinearTVProduct",
    "MakegoodTerms",
    "SupplyPoolEntry",
    # Agent registry
    "AgentAuthentication",
    "AgentCapabilities",
    "AgentCard",
    "AgentProvider",
    "AgentSkill",
    "AgentType",
    "RegisteredAgent",
    "RegistrySource",
    "TrustStatus",
    "TRUST_TO_TIER_MAP",
    # Order state machine
    "OrderStatus",
    "OrderStateMachine",
    "OrderAuditLog",
    "StateTransition",
    "TransitionRule",
    "InvalidTransitionError",
    "from_execution_status",
    "from_execution_order_status",
    # Change request management
    "ChangeRequest",
    "ChangeRequestStatus",
    "ChangeSeverity",
    "ChangeType",
    "FieldDiff",
    "classify_severity",
    "validate_change_request",
    # API key authentication
    "ApiKeyCreateRequest",
    "ApiKeyCreateResponse",
    "ApiKeyInfo",
    "ApiKeyRecord",
]
